version: '3.8'
services:
  front:
    build:
      context: ./pdfmodoock-front
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./pdfmodoock-front:/app
    depends_on:
      - back
  back:
    build:
      context: ./pdfmodoock
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./pdfmodoock:/app